version: "3.9"

services:
  app:
    container_name: supersettings
    image: javimosch/supersettings:latest
    environment:
      - NODE_ENV=production
    working_dir: /app
    expose:
      - "3006"
    env_file:
      - ./.env
    command: ["node", "server.js"]
    networks:
      - coolify-shared
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

networks:
  coolify-shared:
    external: true
